created new module for start/stop ec2 instances by tags using schedul…
cex-solutions/terraform-scheduled-instance-action pull request #1
Opened 2022-04-14 14:36 UTC by cristiansandru11

…ed cloudwatch events

2022-04-14 15:32 UTC, gteodoru commented on code/ec2_lambda_handler.py
> +# Getting instances tagged with Start tag
this should be `Stop`

2022-04-14 15:40 UTC, gteodoru requested changes

2022-04-14 15:40 UTC, gteodoru commented on code/ec2_lambda_handler.py
> +    print('started  instances: ' + str(start_instances))
nothing should be global ... everything should be in methods 

```
def _get_instances_by_tag(tag_name, tag_value):
   .....

def _get_instance_ids(tag_name, tag_value):
  response = _get_instances_by_tag(tag_name, tag_value)
  .....

def stop(event, context):
  tag_name = os.getenv("STOP_TAG_NAME")
  tag_value = os.getenv("STOP_TAG_VALUE")
  instances = _get_instance_ids(tag_name, tag_name)
  ....

def start(event, context):
  tag_name = os.getenv("STOP_TAG_NAME")
  tag_value = os.getenv("STOP_TAG_VALUE")
  instances = _get_instance_ids(tag_name, tag_name)
  ....
```

2022-04-14 15:40 UTC, gteodoru commented on code/ec2_lambda_handler.py
> +    print('started  instances: ' + str(start_instances))
Add logger !!!!! for info

2022-04-14 15:42 UTC, cristiansandru11 commented on code/ec2_lambda_handler.py
> +    print('started  instances: ' + str(start_instances))
❤️  10x

2022-04-15 09:25 UTC, AndreiPencea approved these changes

2022-04-15 09:30 UTC, merged